### ISSUE TITLE
[Code Issue] Client code on server

### ISSUE THREAD

**Issue by XFactHD** [darklordwonton/Advanced-Cables#1]
[This](https://github.com/darklordwonton/Advanced-Cables/blob/master/src/main/java/gggamer/advancedcables/AdvancedCablesMain.java#L239-L282) will crash dedicated servers, you need create a client and a server proxy and do that stuff in the client proxy or wrap it in a check of `FMLCommonHandler.getInstance().getSide().isClient()`.

Also, you should be using `ModelLoader.setCustomModelResourceLocation()` instead of that ItemModelMesher stuff.

**Comment by darklordwonton** [comment]
oh yeah that could cause problems. I'll fix that later today.

**Comment by darklordwonton** [comment]
fixed (6 days ago but I forgot to close the issue)
