### ISSUE TITLE
1.17.10

### ISSUE THREAD

**Issue by BaillisCremey** [darklordwonton/Advanced-Cables#3]
I've seen around on some sites that this mod is available for 1.7.10, but I can't seem to find a link. Do you have one?

**Comment by darklordwonton** [comment]
This mod is currently 1.9.4/1.10.2 only atm (I'll be working on a 1.11.2 port soon) if you've seen a website claiming to have a 1.7.10 version it's probably a spam site.

**Comment by BaillisCremey** [comment]
That's what I figured. I've never actually "downgraded" a mod, so I'm not sure if I will be successful, but would you mind if I attempted to do so with your code?

**Comment by darklordwonton** [comment]
Be my guest
