### ISSUE TITLE
cables melt no matter how much rf flows through them

### ISSUE THREAD

**Issue by megaloloful** [darklordwonton/Advanced-Cables#6]
I tried hooking up a survivalists generator (5rf/t) with high voltage cables and they melted instantly. I'm pretty sure that isn't supposed to happen

**Comment by darklordwonton** [comment]
You are very right about that, I'll look into this ASAP.

**Comment by darklordwonton** [comment]
Does this happen with generators from other mods or just extra utilities?

**Comment by darklordwonton** [comment]
fixed
